# Generated by Django 2.2.1 on 2019-11-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='notice_or_not',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
